#!/usr/bin/env python3
"""Generate the Antigravity (Agent Skills) copies of the Claude Code workflows.

Google Antigravity exposes as `/name` only the skills under
`.agents/skills/<name>/SKILL.md`; it never reads `.claude/`. Pointer files are
followed weakly, so every slash command gets a FULL copy of its instructions.
`.claude/` stays the single source of truth - this script derives the rest:

  .claude/commands/<cmd>.md          -> .agents/skills/<cmd>/SKILL.md
  .claude/skills/<dir>/SKILL.md      -> .agents/skills/<name>/SKILL.md
                                        (job-scraper -> scrape, per its name:)
  every hand-written portal skill    -> .agents/skills/<portal>/.skillignore

Only SKILL.md bodies are copied. The sibling files of the source skills
(01-candidate-profile.md ... 09-web-research.md, search-queries.md) are
runtime-written data: /setup, /reset, /expand, /apply, /add-template and
/add-portal edit them in place. Copying them would let Antigravity edit a
copy that the next sync overwrites, so the generated skills reference them at
their canonical `.claude/skills/...` paths instead.

While copying, Claude-only constructs are rewritten to agent-neutral wording
with Antigravity tool names (WebFetch -> read_url_content, WebSearch ->
search_web, Agent tool -> invoke_subagent or inline, AskUserQuestion -> ask
in chat), Claude-only frontmatter (`allowed-tools`, `model:`, `argument-hint`,
`disable-model-invocation`) is dropped, the `description:` is taken from the
source's own frontmatter, and a header note explains `$ARGUMENTS`.

Usage:
  python3 tools/sync_agent_skills.py           # write/refresh generated files
  python3 tools/sync_agent_skills.py --check   # exit 1 if anything drifted

Run it after editing anything under .claude/commands or .claude/skills, and
after /setup, /reset, /add-template or /add-portal.

Stdlib only. Exit 0 on success / no drift, 1 on drift or a config error.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

GENERATED_MARKER = "GENERATED by tools/sync_agent_skills.py"
HEADER_COMMENT = (
    f"<!-- {GENERATED_MARKER} - edit the source under .claude/ and re-run "
    "(python3 tools/sync_agent_skills.py). Source: {source} -->"
)

# Source skill directory -> generated skill name (the source's `name:`).
SKILL_SOURCES = {
    "job-application-assistant": "job-application-assistant",
    "job-scraper": "scrape",
    "upskill": "upskill",
}

# Version stamped on generated skills whose source carries none.
DEFAULT_FRAMEWORK_VERSION = "1.0.0"

SKILLIGNORE = "node_modules/\n**/node_modules/**\nbun.lock\nbun.lockb\npackage-lock.json\ndist/\n"

def read_text(path: Path) -> str:
    """Read UTF-8 text with line endings normalized to LF (WSL/autocrlf safe)."""
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (flat frontmatter keys, body). Missing frontmatter -> ({}, text)."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    data: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if line and not line[0].isspace() and ":" in line:
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip().strip('"').strip("'")
    body = text[end + 4:]
    return data, body.lstrip("\n")


def frontmatter_description(text: str) -> str:
    """The source's own `description:` frontmatter value, as one line.

    Descriptions live in the .claude/ sources (Claude Code reads them there),
    so the generated copies reuse them instead of keeping a second list here.
    Handles a plain or quoted scalar and folded/literal blocks (`>`, `>-`,
    `|`, `|-`); returns "" when there is no frontmatter or no description.
    """
    if not text.startswith("---\n"):
        return ""
    end = text.find("\n---", 4)
    if end == -1:
        return ""
    lines = text[4:end].splitlines()
    for i, line in enumerate(lines):
        if not line.startswith("description:"):
            continue
        value = line.split(":", 1)[1].strip()
        if value and value[0] not in ">|":
            return value.strip('"').strip("'")
        block = []
        for cont in lines[i + 1:]:
            if cont and not cont[0].isspace():
                break
            block.append(cont.strip())
        return " ".join(part for part in block if part)
    return ""


def data_file_names() -> dict[str, str]:
    """Bare sibling-file name -> canonical repo path, for every source skill."""
    names: dict[str, str] = {}
    for src_dir in SKILL_SOURCES:
        directory = ROOT / ".claude" / "skills" / src_dir
        for path in sorted(directory.glob("*.md")):
            if path.name != "SKILL.md":
                names[path.name] = f".claude/skills/{src_dir}/{path.name}"
    return names


def command_names() -> list[str]:
    return sorted(p.stem for p in (ROOT / ".claude" / "commands").glob("*.md"))


def rewrite_body(body: str) -> str:
    """Rewrite Claude-only constructs into Antigravity / agent-neutral wording."""
    # Skill entry points: point at the generated (translated) copies.
    for cmd in command_names():
        body = body.replace(f".claude/commands/{cmd}.md", f".agents/skills/{cmd}/SKILL.md")
    for src_dir, name in SKILL_SOURCES.items():
        body = body.replace(f".claude/skills/{src_dir}/SKILL.md", f".agents/skills/{name}/SKILL.md")

    # Data files stay canonical under .claude/: qualify bare sibling references
    # (they would otherwise resolve against .agents/skills/<name>/).
    for name, canonical in data_file_names().items():
        body = re.sub(rf"(?<![\w./-]){re.escape(name)}", canonical, body)
    body = body.replace(" (this directory)", "")

    # Tool names.
    body = re.sub(r"\bWebFetch\b", "read_url_content", body)
    body = re.sub(r"\bWebSearch\b", "search_web", body)
    body = re.sub(
        r"(?:the )?\*{0,2}Agent tool\*{0,2}",
        "`invoke_subagent` (if available; otherwise do the work inline yourself)",
        body,
    )
    body = body.replace("`general-purpose` agents", "general-purpose subagents")
    body = body.replace("`general-purpose`", "general-purpose")
    body = re.sub(r"\bthe AskUserQuestion tool\b", "a question in chat", body)
    body = re.sub(r"\bAskUserQuestion\b", "ask the user in chat", body)
    body = re.sub(r"\bGlob with\b", "a glob file search with", body)
    return body


def header_note(name: str, is_command: bool) -> str:
    invocation = f"`/{name}`"
    lines = [
        f"> **Antigravity copy of {invocation}.**"
        + (
            f" Invoked as {invocation}; any text the user typed after the command is "
            "referred to below as `$ARGUMENTS` (empty if nothing followed it)."
            if is_command or name in ("scrape", "upskill")
            else ""
        ),
        "> Follow the steps below exactly and in order - never substitute a built-in "
        "or guided flow. Tool names: read_url_content = fetch a URL, search_web = web "
        "search, `invoke_subagent` = subagent (if unavailable, do the work inline); "
        "Read/Write/Edit/Bash tool = your file and terminal tools. Paths are relative "
        "to the repository root; profile and data files live under "
        "`.claude/skills/...` - read and write them there, except that a gitignored "
        "`<file>.personal` beside one takes precedence: read it instead, and write "
        "candidate data only to it (Personal overlay).",
    ]
    if name == "job-application-assistant":
        lines[0] = "> **Antigravity copy of the job-application-assistant skill.**"
    return "\n".join(lines)


def yaml_folded(text: str) -> str:
    words = text.split()
    out, line = [], ""
    for word in words:
        if line and len(line) + 1 + len(word) > 86:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}" if line else word
    if line:
        out.append(line)
    return "\n".join(f"  {ln}" for ln in out)


def render(name: str, source: Path, is_command: bool) -> str:
    text = read_text(source)
    fm, body = split_frontmatter(text)
    description = frontmatter_description(text)
    if not description:
        sys.exit(
            f"sync_agent_skills: no description for '{name}' - add a `description:` "
            f"to the frontmatter of {source.relative_to(ROOT).as_posix()}"
        )
    version = fm.get("framework_version") or DEFAULT_FRAMEWORK_VERSION
    rel_source = source.relative_to(ROOT).as_posix()
    parts = [
        "---",
        f"name: {name}",
        "description: >-",
        yaml_folded(description),
        f"framework_version: {version}",
        "---",
        HEADER_COMMENT.format(source=rel_source),
        "",
        header_note(name, is_command),
        "",
        rewrite_body(body).rstrip("\n"),
        "",
    ]
    return "\n".join(parts)


def guard_hand_written(target: Path) -> None:
    """Never overwrite a hand-written skill (e.g. a portal) that shares a name."""
    if target.is_file() and GENERATED_MARKER not in read_text(target):
        sys.exit(
            f"sync_agent_skills: refusing to overwrite hand-written skill {rel(target)} - "
            "rename the .claude/ source that maps to it"
        )


def expected_outputs() -> dict[Path, str]:
    """Every generated path -> its exact expected content."""
    outputs: dict[Path, str] = {}
    skills_root = ROOT / ".agents" / "skills"
    generated_names: set[str] = set()

    for cmd in command_names():
        source = ROOT / ".claude" / "commands" / f"{cmd}.md"
        guard_hand_written(skills_root / cmd / "SKILL.md")
        outputs[skills_root / cmd / "SKILL.md"] = render(cmd, source, True)
        generated_names.add(cmd)
    for src_dir, name in SKILL_SOURCES.items():
        source = ROOT / ".claude" / "skills" / src_dir / "SKILL.md"
        if not source.is_file():
            continue
        if name in generated_names:
            sys.exit(f"sync_agent_skills: name collision - '{name}' is both a command and a skill")
        guard_hand_written(skills_root / name / "SKILL.md")
        outputs[skills_root / name / "SKILL.md"] = render(name, source, False)
        generated_names.add(name)

    # Hand-written portal skills: every other skill dir gets a .skillignore.
    if skills_root.is_dir():
        for directory in sorted(p for p in skills_root.iterdir() if p.is_dir()):
            if directory.name in generated_names:
                continue
            skill_md = directory / "SKILL.md"
            if skill_md.is_file() and GENERATED_MARKER in read_text(skill_md):
                continue  # stale generated skill, handled by stale_outputs()
            outputs[directory / ".skillignore"] = SKILLIGNORE
    return outputs


def stale_outputs(expected: dict[Path, str]) -> list[Path]:
    """Generated SKILL.md files whose source no longer exists."""
    skills_root = ROOT / ".agents" / "skills"
    stale = []
    for skill_md in sorted(skills_root.glob("*/SKILL.md")):
        if skill_md in expected:
            continue
        if GENERATED_MARKER in read_text(skill_md):
            stale.append(skill_md)
    return stale


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="report drift and exit 1 instead of writing")
    args = parser.parse_args(argv)

    expected = expected_outputs()
    drifted = [
        path for path, content in expected.items()
        if not path.is_file() or read_text(path) != content
    ]
    stale = stale_outputs(expected)

    if args.check:
        if not drifted and not stale:
            print(f"sync_agent_skills: OK ({len(expected)} generated files in sync)")
            return 0
        print("sync_agent_skills: .agents/skills is out of sync with .claude/ - run python3 tools/sync_agent_skills.py")
        for path in drifted:
            print(f"  - {'missing' if not path.is_file() else 'drifted'}: {rel(path)}")
        for path in stale:
            print(f"  - stale (source removed): {rel(path)}")
        return 1

    for path in drifted:
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(expected[path])
        print(f"  wrote {rel(path)}")
    for path in stale:
        path.unlink()
        print(f"  removed stale {rel(path)}")
        try:
            path.parent.rmdir()
        except OSError:
            pass
    print(f"sync_agent_skills: {len(drifted)} written, {len(stale)} removed, {len(expected)} total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
