#!/usr/bin/env python3
"""Generate the Antigravity (Agent Skills) copies of the Claude Code workflows.

Google Antigravity exposes as `/name` only the skills under
`.agents/skills/<name>/SKILL.md`; it never reads `.claude/`. Pointer files are
followed weakly, so every slash command gets a FULL copy of its instructions.
`.claude/` stays the single source of truth - this script derives the rest:

  .claude/commands/<cmd>.md          -> .agents/skills/<cmd>/SKILL.md
  .claude/skills/<dir>/SKILL.md      -> .agents/skills/<name>/SKILL.md
                                        (job-scraper -> scrape, per its name:)
  every hand-written portal skill    -> .agents/skills/<portal>/.skillignore

Only SKILL.md bodies are copied. The sibling files of the source skills
(01-candidate-profile.md ... 09-web-research.md, search-queries.md) are
runtime-written data: /setup, /reset, /expand, /apply, /add-template and
/add-portal edit them in place. Copying them would let Antigravity edit a
copy that the next sync overwrites, so the generated skills reference them at
their canonical `.claude/skills/...` paths instead.

While copying, Claude-only constructs are rewritten to agent-neutral wording
with Antigravity tool names (WebFetch -> read_url_content, WebSearch ->
search_web, Agent tool -> invoke_subagent or inline, AskUserQuestion -> ask
in chat, `mcp__<server>__<tool>` -> "the <server> MCP tool", "read the PDF via
the Read tool" -> render and inspect the PDF visually), `model:` frontmatter is
dropped, `allowed-tools` becomes a tool-neutral "Tools this skill needs" line,
every description gains "Also triggered by /<name>.", and a header note explains
`$ARGUMENTS`. Generated output that still contains a Claude-only token
(FORBIDDEN_TOKENS) is an error in both write and --check mode.

Usage:
  python3 tools/sync_agent_skills.py           # write/refresh generated files
  python3 tools/sync_agent_skills.py --check   # exit 1 if anything drifted

Run it after editing anything under .claude/commands or .claude/skills, and
after /setup, /reset, /add-template or /add-portal.

Stdlib only. Exit 0 on success / no drift, 1 on drift or a config error.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

GENERATED_MARKER = "GENERATED by tools/sync_agent_skills.py"
HEADER_COMMENT = (
    f"<!-- {GENERATED_MARKER} - edit the source under .claude/ and re-run "
    "(python3 tools/sync_agent_skills.py). Source: {source} -->"
)

# Source skill directory -> generated skill name (the source's `name:`).
SKILL_SOURCES = {
    "job-application-assistant": "job-application-assistant",
    "job-scraper": "scrape",
    "upskill": "upskill",
}

# Claude-only tokens that must never survive into a generated skill. A source
# phrasing the rewrites below do not cover fails the sync loudly instead of
# shipping a tool name Antigravity does not have.
FORBIDDEN_TOKENS = ("mcp__", "AskUserQuestion", "WebFetch", "WebSearch", "Agent tool")

# Antigravity caps a skill description at 1024 characters.
MAX_DESCRIPTION_CHARS = 1024

# Version stamped on generated skills whose source carries none.
DEFAULT_FRAMEWORK_VERSION = "1.0.0"

SKILLIGNORE = "node_modules/\n**/node_modules/**\nbun.lock\nbun.lockb\npackage-lock.json\ndist/\n"

# Trigger-friendly descriptions. The primary agent picks skills by these, so
# each names the slash command and the plain-language requests it covers.
DESCRIPTIONS = {
    "apply": (
        "Runs the full /apply drafter-reviewer job application workflow: fit "
        "evaluation, tailored CV (exactly 2 pages) and cover letter (1 page), "
        "review, compile, quality gate and tracker update. Use when the user types "
        "/apply or asks to apply to, tailor a CV for, or write a cover letter for a "
        "specific job posting (URL or pasted text)."
    ),
    "rank": (
        "Runs /rank: batch-scores scraped jobs in job_scraper/seen_jobs.json against "
        "the fit framework and returns a ranked shortlist. Use when the user types "
        "/rank or asks to rank, triage, score or shortlist the scraped jobs."
    ),
    "setup": (
        "Runs /setup profile onboarding: collects the candidate's career information "
        "and populates CLAUDE.md, the profile files and search queries. Use when the "
        "user types /setup or asks to set up, onboard, or (re)build their candidate "
        "profile."
    ),
    "interview": (
        "Runs /interview: builds a stage-specific interview prep pack (and optional "
        "mock interview) for a tracked application. Use when the user types "
        "/interview or asks to prepare for an upcoming interview with a company."
    ),
    "outcome": (
        "Runs /outcome: records the result or progress of a tracked application "
        "(interview, offer, rejection, no response) and drafts follow-ups for stale "
        "ones. Use when the user types /outcome or reports news about an application."
    ),
    "expand": (
        "Runs /expand: discovers competencies hidden in the user's documents and "
        "public online presence and proposes additive profile updates. Use when the "
        "user types /expand or asks to enrich or expand their profile/competencies."
    ),
    "reset": (
        "Runs /reset: destructively resets profile files and/or the documents folder "
        "to a blank state after explicit confirmation. Use only when the user types "
        "/reset or explicitly asks to reset or wipe their profile data."
    ),
    "gmail-sync": (
        "Runs /gmail-sync: scans Gmail for status signals on tracked applications "
        "and, after approval, updates the tracker and outcome files. Use when the "
        "user types /gmail-sync or asks to sync application status from email."
    ),
    "notion-sync": (
        "Runs /notion-sync: pushes ranked jobs and applications to a read-only Notion "
        "database view. Use when the user types /notion-sync or asks to sync the job "
        "search to Notion."
    ),
    "html-report": (
        "Runs /html-report: generates a self-contained HTML dashboard from the "
        "application tracker. Use when the user types /html-report or asks for an "
        "application dashboard or tracker report."
    ),
    "add-portal": (
        "Runs /add-portal: investigates a job board and scaffolds a new portal search "
        "skill (CLI) for it. Use when the user types /add-portal or asks to add "
        "support for a new job portal or job board."
    ),
    "add-template": (
        "Runs /add-template: registers, lists or switches a custom CV or cover letter "
        "template. Use when the user types /add-template or asks to use their own CV "
        "or cover letter template."
    ),
    "scrape": (
        "Runs /scrape: finds new job postings matching the profile across all "
        "installed portal-search CLIs and deduplicates them across runs. Use when the "
        "user types /scrape or asks to find, search or scrape new jobs in general "
        "(without naming a single portal)."
    ),
    "upskill": (
        "Runs /upskill: compares tracked job postings against the candidate profile "
        "to find skill gaps and produce a prioritized learning plan. Use when the "
        "user types /upskill or asks about skill gaps, what to learn, or a learning "
        "plan."
    ),
    "job-application-assistant": (
        "Assists with ad-hoc job application work outside a slash command: "
        "evaluating a job posting's fit, tailoring CVs, writing cover letters, "
        "answering application-form questions and interview prep. Use when the user "
        "asks about a job posting, CV, cover letter, resume, job fit or interview "
        "prep without typing a slash command."
    ),
}


def read_text(path: Path) -> str:
    """Read UTF-8 text with line endings normalized to LF (WSL/autocrlf safe)."""
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def split_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (flat frontmatter keys, body). Missing frontmatter -> ({}, text)."""
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    data: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if line and not line[0].isspace() and ":" in line:
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip().strip('"').strip("'")
    body = text[end + 4:]
    return data, body.lstrip("\n")


def data_file_names() -> dict[str, str]:
    """Bare sibling-file name -> canonical repo path, for every source skill."""
    names: dict[str, str] = {}
    for src_dir in SKILL_SOURCES:
        directory = ROOT / ".claude" / "skills" / src_dir
        for path in sorted(directory.glob("*.md")):
            if path.name != "SKILL.md":
                names[path.name] = f".claude/skills/{src_dir}/{path.name}"
    return names


def command_names() -> list[str]:
    return sorted(p.stem for p in (ROOT / ".claude" / "commands").glob("*.md"))


def rewrite_body(body: str) -> str:
    """Rewrite Claude-only constructs into Antigravity / agent-neutral wording."""
    # Skill entry points: point at the generated (translated) copies.
    for cmd in command_names():
        body = body.replace(f".claude/commands/{cmd}.md", f".agents/skills/{cmd}/SKILL.md")
    for src_dir, name in SKILL_SOURCES.items():
        body = body.replace(f".claude/skills/{src_dir}/SKILL.md", f".agents/skills/{name}/SKILL.md")

    # Data files stay canonical under .claude/: qualify bare sibling references
    # (they would otherwise resolve against .agents/skills/<name>/).
    for name, canonical in data_file_names().items():
        body = re.sub(rf"(?<![\w./-]){re.escape(name)}", canonical, body)
    body = body.replace(" (this directory)", "")

    # MCP tool names: Gmail and Notion first (their tail may be `*`, a tool
    # name or empty, as in "tool names starting with `mcp__notion__`"), then
    # any other server.
    # A parenthetical that only names the tool prefix repeats the prose around
    # it ("the Gmail MCP tools (`mcp__claude_ai_Gmail__*`)"): drop it.
    body = re.sub(r" \(`mcp__[\w-]*\*?`\)", "", body)
    body = re.sub(
        r"tool names starting with `?mcp__(?:claude_ai_)?([\w-]+?)__`?",
        lambda m: f"tool names from the {m.group(1).capitalize()} MCP server",
        body,
    )
    body = re.sub(r"`?mcp__(?:claude_ai_)?[Gg]mail__(\*|\w+)?`?", _mcp_named("Gmail"), body)
    body = re.sub(r"`?mcp__(?:claude_ai_)?[Nn]otion__(\*|[\w-]+)?`?", _mcp_named("Notion"), body)
    body = re.sub(r"`?mcp__([\w-]+?)__(\*|[\w-]+)?`?", _mcp_generic, body)

    # Visual PDF inspection: Antigravity has no PDF-reading Read tool.
    body = PDF_READ_PHRASE.sub(_pdf_inspect, body)

    # Tool names.
    body = re.sub(r"\bWebFetch\b", "read_url_content", body)
    body = re.sub(r"\bWebSearch\b", "search_web", body)
    body = re.sub(
        r"(?:the )?\*{0,2}Agent tool\*{0,2}",
        "`invoke_subagent` (if available; otherwise do the work inline yourself)",
        body,
    )
    body = body.replace("`general-purpose` agents", "general-purpose subagents")
    body = body.replace("`general-purpose`", "general-purpose")
    body = re.sub(r"\bthe AskUserQuestion tool\b", "a question in chat", body)
    body = re.sub(r"\bAskUserQuestion\b", "ask the user in chat", body)
    body = re.sub(r"\bGlob with\b", "a glob file search with", body)
    return body


PDF_INSPECT = (
    "open the compiled PDF and inspect each page visually (render to images if your "
    "runtime cannot view PDFs)"
)
PDF_READ_PHRASE = re.compile(
    r"\b[Rr]ead (?:both |the |each )?(?:compiled )?PDFs? (?:output )?(?:via|with|using) the Read tool"
    r"|\b(?:[Uu]se )?(?:the )?Read tool on the (?:compiled )?PDFs?(?: output)?"
)


def _pdf_inspect(match: "re.Match[str]") -> str:
    text = PDF_INSPECT
    if "both" in match.group(0):
        text = text.replace("the compiled PDF", "both compiled PDFs")
    if match.group(0)[0].isupper():
        text = text[0].upper() + text[1:]
    return text


def _mcp_named(label: str):
    def replace(match: "re.Match[str]") -> str:
        tool = match.group(1)
        if not tool or tool == "*":
            return f"the {label} MCP tools"
        return f"the {label} MCP tools ({tool})"
    return replace


def _mcp_generic(match: "re.Match[str]") -> str:
    server, tool = re.sub(r"^claude_ai_", "", match.group(1)), match.group(2)
    if not tool or tool == "*":
        return f"the {server} MCP tools"
    return f"the {server} MCP tool `{tool}`"


def _split_tools(value: str) -> list[str]:
    """Split an allowed-tools value on commas outside parentheses."""
    items, depth, current = [], 0, ""
    for ch in value:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth = max(0, depth - 1)
        if ch == "," and depth == 0:
            items.append(current.strip())
            current = ""
        else:
            current += ch
    if current.strip():
        items.append(current.strip())
    return items


def tools_needed(allowed: str) -> str:
    """Translate Claude Code `allowed-tools` into a tool-neutral sentence."""
    if not allowed:
        return ""
    groups: list[str] = []
    commands: list[str] = []

    def add(label: str) -> None:
        if label not in groups:
            groups.append(label)

    for item in _split_tools(allowed):
        name, _, arg = item.partition("(")
        name, arg = name.strip(), arg.rstrip(")").strip()
        if name in ("Read", "Glob", "Grep"):
            add("read and search files")
        elif name in ("Write", "Edit", "MultiEdit", "NotebookEdit"):
            add("write and edit files")
        elif name == "Bash":
            add("terminal")
            if arg:
                cmd = re.sub(r"(?::\*| \*)$", "", arg).strip()
                if cmd and cmd not in commands:
                    commands.append(cmd)
        elif name == "WebFetch":
            add("fetch URLs (read_url_content)")
        elif name == "WebSearch":
            add("web search (search_web)")
        elif name in ("Agent", "Task"):
            add("subagents (`invoke_subagent` if available, otherwise inline)")
        elif name == "AskUserQuestion":
            add("ask the user in chat")
        elif name.startswith("mcp__"):
            add(re.sub(r"`?mcp__([\w-]+?)__(\*|[\w-]+)?`?", _mcp_generic, name))
        # Skill(...) and unknown entries carry no runtime-neutral meaning.
    if "terminal" in groups and commands:
        groups[groups.index("terminal")] = "terminal (" + ", ".join(f"`{c}`" for c in commands) + ")"
    return "Tools this skill needs: " + "; ".join(groups) + "." if groups else ""


def description_for(name: str) -> str:
    text = f"{DESCRIPTIONS[name]} Also triggered by /{name}."
    if len(text) > MAX_DESCRIPTION_CHARS:
        sys.exit(
            f"sync_agent_skills: description for '{name}' is {len(text)} characters "
            f"(max {MAX_DESCRIPTION_CHARS}) - shorten it in DESCRIPTIONS"
        )
    return text


def forbidden_tokens(text: str) -> list[str]:
    return [token for token in FORBIDDEN_TOKENS if token in text]


def header_note(name: str, is_command: bool, tools_line: str = "") -> str:
    invocation = f"`/{name}`"
    lines = [
        f"> **Antigravity copy of {invocation}.**"
        + (
            f" Invoked as {invocation}; any text the user typed after the command is "
            "referred to below as `$ARGUMENTS` (empty if nothing followed it)."
            if is_command or name in ("scrape", "upskill")
            else ""
        ),
        "> Follow the steps below exactly and in order - never substitute a built-in "
        "or guided flow. Tool names: read_url_content = fetch a URL, search_web = web "
        "search, `invoke_subagent` = subagent (if unavailable, do the work inline); "
        "Read/Write/Edit/Bash tool = your file and terminal tools. Paths are relative "
        "to the repository root; profile and data files live under "
        "`.claude/skills/...` - read and write them there.",
    ]
    if name == "job-application-assistant":
        lines[0] = "> **Antigravity copy of the job-application-assistant skill.**"
    if tools_line:
        lines.append(f"> {tools_line}")
    return "\n".join(lines)


def yaml_folded(text: str) -> str:
    words = text.split()
    out, line = [], ""
    for word in words:
        if line and len(line) + 1 + len(word) > 86:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}" if line else word
    if line:
        out.append(line)
    return "\n".join(f"  {ln}" for ln in out)


def render(name: str, source: Path, is_command: bool) -> str:
    fm, body = split_frontmatter(read_text(source))
    if name not in DESCRIPTIONS:
        sys.exit(
            f"sync_agent_skills: no description for '{name}' - add one to DESCRIPTIONS "
            "in tools/sync_agent_skills.py"
        )
    version = fm.get("framework_version") or DEFAULT_FRAMEWORK_VERSION
    rel_source = source.relative_to(ROOT).as_posix()
    parts = [
        "---",
        f"name: {name}",
        "description: >-",
        yaml_folded(description_for(name)),
        f"framework_version: {version}",
        "---",
        HEADER_COMMENT.format(source=rel_source),
        "",
        header_note(name, is_command, tools_needed(fm.get("allowed-tools", ""))),
        "",
        rewrite_body(body).rstrip("\n"),
        "",
    ]
    return "\n".join(parts)


def guard_hand_written(target: Path) -> None:
    """Never overwrite a hand-written skill (e.g. a portal) that shares a name."""
    if target.is_file() and GENERATED_MARKER not in read_text(target):
        sys.exit(
            f"sync_agent_skills: refusing to overwrite hand-written skill {rel(target)} - "
            "rename the .claude/ source that maps to it"
        )


def expected_outputs() -> dict[Path, str]:
    """Every generated path -> its exact expected content."""
    outputs: dict[Path, str] = {}
    skills_root = ROOT / ".agents" / "skills"
    generated_names: set[str] = set()

    for cmd in command_names():
        source = ROOT / ".claude" / "commands" / f"{cmd}.md"
        guard_hand_written(skills_root / cmd / "SKILL.md")
        outputs[skills_root / cmd / "SKILL.md"] = render(cmd, source, True)
        generated_names.add(cmd)
    for src_dir, name in SKILL_SOURCES.items():
        source = ROOT / ".claude" / "skills" / src_dir / "SKILL.md"
        if not source.is_file():
            continue
        if name in generated_names:
            sys.exit(f"sync_agent_skills: name collision - '{name}' is both a command and a skill")
        guard_hand_written(skills_root / name / "SKILL.md")
        outputs[skills_root / name / "SKILL.md"] = render(name, source, False)
        generated_names.add(name)

    # Hand-written portal skills: every other skill dir gets a .skillignore.
    if skills_root.is_dir():
        for directory in sorted(p for p in skills_root.iterdir() if p.is_dir()):
            if directory.name in generated_names:
                continue
            skill_md = directory / "SKILL.md"
            if skill_md.is_file() and GENERATED_MARKER in read_text(skill_md):
                continue  # stale generated skill, handled by stale_outputs()
            outputs[directory / ".skillignore"] = SKILLIGNORE
    return outputs


def stale_outputs(expected: dict[Path, str]) -> list[Path]:
    """Generated SKILL.md files whose source no longer exists."""
    skills_root = ROOT / ".agents" / "skills"
    stale = []
    for skill_md in sorted(skills_root.glob("*/SKILL.md")):
        if skill_md in expected:
            continue
        if GENERATED_MARKER in read_text(skill_md):
            stale.append(skill_md)
    return stale


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--check", action="store_true", help="report drift and exit 1 instead of writing")
    args = parser.parse_args(argv)

    expected = expected_outputs()
    leaks = {path: forbidden_tokens(content) for path, content in expected.items()}
    leaks = {path: tokens for path, tokens in leaks.items() if tokens}
    if leaks:
        print(
            "sync_agent_skills: generated skills still contain Claude-only tokens - extend "
            "rewrite_body() in tools/sync_agent_skills.py or reword the .claude/ source:"
        )
        for path, tokens in leaks.items():
            print(f"  - {rel(path)}: {', '.join(tokens)}")
        return 1
    drifted = [
        path for path, content in expected.items()
        if not path.is_file() or read_text(path) != content
    ]
    stale = stale_outputs(expected)

    if args.check:
        if not drifted and not stale:
            print(f"sync_agent_skills: OK ({len(expected)} generated files in sync)")
            return 0
        print("sync_agent_skills: .agents/skills is out of sync with .claude/ - run python3 tools/sync_agent_skills.py")
        for path in drifted:
            print(f"  - {'missing' if not path.is_file() else 'drifted'}: {rel(path)}")
        for path in stale:
            print(f"  - stale (source removed): {rel(path)}")
        return 1

    for path in drifted:
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(expected[path])
        print(f"  wrote {rel(path)}")
    for path in stale:
        path.unlink()
        print(f"  removed stale {rel(path)}")
        try:
            path.parent.rmdir()
        except OSError:
            pass
    print(f"sync_agent_skills: {len(drifted)} written, {len(stale)} removed, {len(expected)} total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
